export const projects = [
  {
    title: 'MERN Memories',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'WebRTC App',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/3.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Personal Portfolio',
    description: "This is a simple Portfolio has fully responsive interface, contains forms to fill up the interest in a person Azure cloud services",
    image: '/images/portfolioLandingPage.png',
    tags: ['ASP.NET', 'MVC', 'C#', 'HTML5'],
    source: 'https://afportfolio2022.azurewebsites.net',
    visit: 'https://afportfolio2022.azurewebsites.net',
    id: 4,
  },
];

export const TimeLineData = [
  { year: '2004-2008', text: 'Bachelor of Science Biotechnology  @Bar ilan University Israel ', },
  { year: '2010-2017', text: 'R&D Manager @Coca-Cola Bottling company Israel', },
  { year: '2018-2019', text: 'Started my journey with Java EE @Go2IT ', },
  { year: '2017-2022', text: 'QA and regulatory specialist @Fierafoods.com', },
  { year: '2019-2020', text: 'Continued develope Java @Conestoga Cambridge ON', },
  { year: '2021-2022', text: 'Web App Developer @triOS college Kitchener ON', },
  { year: '2022-present', text: 'Full-stack Developer @GrowMushroomsCanada.ca', },
];